[2025-10-03T15:51:46.266+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-03T15:51:46.349+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps manual__2025-10-03T15:51:28.625359+00:00 [queued]>
[2025-10-03T15:51:46.373+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_deps manual__2025-10-03T15:51:28.625359+00:00 [queued]>
[2025-10-03T15:51:46.374+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-03T15:51:46.413+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-10-03 15:51:28.625359+00:00
[2025-10-03T15:51:46.435+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=221) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-03T15:51:46.440+0000] {standard_task_runner.py:64} INFO - Started process 230 to run task
[2025-10-03T15:51:46.440+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'dbt_deps', 'manual__2025-10-03T15:51:28.625359+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp_xtzv3nb']
[2025-10-03T15:51:46.451+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask dbt_deps
[2025-10-03T15:51:46.573+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_dag.dbt_deps manual__2025-10-03T15:51:28.625359+00:00 [running]> on host 88331542f089
[2025-10-03T15:51:46.779+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-10-03T15:51:28.625359+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-03T15:51:28.625359+00:00'
[2025-10-03T15:51:46.783+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-03T15:51:46.791+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-03T15:51:46.793+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && DBT_PROFILES_DIR=/opt/***/dbt dbt deps']
[2025-10-03T15:51:46.817+0000] {subprocess.py:86} INFO - Output:
[2025-10-03T15:51:54.805+0000] {subprocess.py:93} INFO - [0m15:51:54  Running with dbt=1.10.13
[2025-10-03T15:51:55.482+0000] {subprocess.py:93} INFO - [0m15:51:55  Warning: No packages were found in packages.yml
[2025-10-03T15:51:55.488+0000] {subprocess.py:93} INFO - [0m15:51:55  Warning: No packages were found in packages.yml
[2025-10-03T15:51:56.990+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-03T15:51:56.993+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-03T15:51:57.033+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_dag, task_id=dbt_deps, run_id=manual__2025-10-03T15:51:28.625359+00:00, execution_date=20251003T155128, start_date=20251003T155146, end_date=20251003T155157
[2025-10-03T15:51:57.085+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-03T15:51:57.121+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-03T15:51:57.128+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
